### ISSUE TITLE
Puck detection doesn't work. Error while Analyzing color

### ISSUE THREAD

**Issue by Kl0ibi** [OndraSlama/PiHockey#1]
Error during puck detection.
Error during puck detection.
Error during puck detection.
Saving found color...
 Exception in thread Thread-11:
 Traceback (most recent call last):
   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.7/threading.py", line 865, in run
     self._target(*self._args, **self._kwargs)
   File "/home/pi/Documents/PiHockey/Camera.py", line 211, in analyzeColor
     self.callback(results)
   File "/home/pi/Documents/PiHockey/App/airhockey.kv", line 1084, in <lambda>
     on_release: app.root.camera.startAnalyzing(lambda results: app.root.openPopup("Camera", results))
   File "/home/pi/Documents/PiHockey/App/AirHockeyApp.py", line 700, in openPopup
     infoPopup = CustomPopup()
   File "/usr/local/lib/python3.7/dist-packages/kivy/uix/modalview.py", line 195, in __init__
     super(ModalView, self).__init__(**kwargs)
   File "/usr/local/lib/python3.7/dist-packages/kivy/uix/anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "/usr/local/lib/python3.7/dist-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/usr/local/lib/python3.7/dist-packages/kivy/uix/widget.py", line 361, in __init__
     self.canvas = Canvas(opacity=self.opacity)
   File "kivy/graphics/instructions.pyx", line 608, in kivy.graphics.instructions.Canvas.__init__
   File "kivy/graphics/instructions.pyx", line 154, in kivy.graphics.instructions.InstructionGroup.__init__
   File "kivy/graphics/instructions.pyx", line 60, in kivy.graphics.instructions.Instruction.__init__
 TypeError: Cannot create graphics instruction outside the main Kivy thread
 
Error during puck detection.
Error during puck detection.

**Comment by Kl0ibi** [comment]
Use kivy 1.11.1 or lower

and

pygame 1.9.5
